# Generated by Django 5.1.3 on 2024-11-20 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_funcionario_cargo_funcionario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroponto',
            old_name='checkout',
            new_name='saida',
        ),
        migrations.RemoveField(
            model_name='registroponto',
            name='checkin',
        ),
        migrations.AddField(
            model_name='registroponto',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
